CREATE TABLE accounts (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	customer_id INT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
	account_type TEXT NOT NULL,
	balance NUMERIC(18, 2)  NOT NULL DEFAULT 0 CHECK(balance >= 0),
	currency CHAR(3)  NOT NULL DEFAULT ‘USD’,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
